USE BD_ELEICAO

--NUMERO DE VOTOS POR CARGO
SELECT C.CARGO,ISNULL(SUM(V.QUANTIDADE_VOTOS),0) TOTAL
FROM FATO_VOTO V
RIGHT JOIN DIM_CARGO C
ON(V.ID_CARGO = C.ID_CARGO)
RIGHT JOIN DIM_TEMPO T
ON (V.DIA_VOTACAO = T.ID_TEMPO)
WHERE T.ANO = '2022' AND T.TURNO = '1ºTURNO'
GROUP BY C.CARGO

-- NUMERO DE VOTOS POR CARGO NO 2 TURNO
SELECT C.CARGO,ISNULL(SUM(V.QUANTIDADE_VOTOS),0) TOTAL
FROM FATO_VOTO V
RIGHT JOIN DIM_CARGO C
ON(V.ID_CARGO = C.ID_CARGO)
RIGHT JOIN DIM_TEMPO T
ON (V.DIA_VOTACAO = T.ID_TEMPO)
WHERE T.ANO = '2022' AND T.TURNO = '2ºTURNO'
GROUP BY C.CARGO

--NUMERO DE VOTOS POR PARTIDO
SELECT C.PARTIDO,ISNULL(SUM(V.QUANTIDADE_VOTOS),0) TOTAL
FROM FATO_VOTO V
RIGHT JOIN DIM_CANDIDATO C
ON(V.ID_CANDIDATO = C.ID_CANDIDATO)
RIGHT JOIN DIM_TEMPO T
ON (V.DIA_VOTACAO = T.ID_TEMPO)
WHERE T.ANO = '2022' AND T.TURNO = '1ºTURNO'
GROUP BY C.PARTIDO

--NUMERO DE VOTOS POR PARTIDO NO 2 TURNO
SELECT C.PARTIDO,ISNULL(SUM(V.QUANTIDADE_VOTOS),0) TOTAL
FROM FATO_VOTO V
RIGHT JOIN DIM_CANDIDATO C
ON(V.ID_CANDIDATO = C.ID_CANDIDATO)
RIGHT JOIN DIM_TEMPO T
ON (V.DIA_VOTACAO = T.ID_TEMPO)
WHERE T.ANO = '2022' AND T.TURNO = '2ºTURNO'
GROUP BY C.PARTIDO


--NUMERO DE VOTOS POR SESSÃO
SELECT S.NM_SECAO,ISNULL(SUM(V.QUANTIDADE_VOTOS),0) TOTAL
FROM FATO_VOTO V
RIGHT JOIN DIM_SECAO S
ON(V.ID_SECAO = S.ID_SECAO)
RIGHT JOIN DIM_TEMPO T
ON (V.DIA_VOTACAO = T.ID_TEMPO)
WHERE T.ANO = '2022' AND T.TURNO = '1ºTURNO'
GROUP BY S.NM_SECAO

--NUMERO DE VOTOS POR SESSÃO NO 2 TURNO
SELECT S.NM_SECAO,ISNULL(SUM(V.QUANTIDADE_VOTOS),0) TOTAL
FROM FATO_VOTO V
RIGHT JOIN DIM_SECAO S
ON(V.ID_SECAO = S.ID_SECAO)
RIGHT JOIN DIM_TEMPO T
ON (V.DIA_VOTACAO = T.ID_TEMPO)
WHERE T.ANO = '2022' AND T.TURNO = '2ºTURNO'
GROUP BY S.NM_SECAO

--NUMERO DE VOTOS POR TIPO DO VOTO(BRANCOS)
SELECT T.TIPO_VOTO,ISNULL(SUM(V.QUANTIDADE_VOTOS),0) TOTAL
FROM FATO_VOTO V
RIGHT JOIN DIM_TIPO_VOTO T
ON(V.ID_TIPO_VOTO = T.ID_TIPO_VOTO)
RIGHT JOIN DIM_TEMPO TE
ON (V.DIA_VOTACAO = TE.ID_TEMPO)
WHERE TE.ANO = '2022' AND TE.TURNO = '1ºTURNO' AND T.TIPO_VOTO = 'BRANCOS'
GROUP BY T.TIPO_VOTO

--NUMERO DE VOTOS POR TIPO DO VOTO(BRANCOS) NO 2 TURNO
SELECT T.TIPO_VOTO,ISNULL(SUM(V.QUANTIDADE_VOTOS),0) TOTAL
FROM FATO_VOTO V
RIGHT JOIN DIM_TIPO_VOTO T
ON(V.ID_TIPO_VOTO = T.ID_TIPO_VOTO)
RIGHT JOIN DIM_TEMPO TE
ON (V.DIA_VOTACAO = TE.ID_TEMPO)
WHERE TE.ANO = '2022' AND TE.TURNO = '2ºTURNO' AND T.TIPO_VOTO = 'BRANCOS'
GROUP BY T.TIPO_VOTO

--NUMERO DE VOTOS POR TIPO DO VOTO(NULOS)
SELECT T.TIPO_VOTO,ISNULL(SUM(V.QUANTIDADE_VOTOS),0) TOTAL
FROM FATO_VOTO V
RIGHT JOIN DIM_TIPO_VOTO T
ON(V.ID_TIPO_VOTO = T.ID_TIPO_VOTO)
RIGHT JOIN DIM_TEMPO TE
ON (V.DIA_VOTACAO = TE.ID_TEMPO)
WHERE T.TIPO_VOTO = 'NULOS' AND TE.ANO = '2022' AND TE.TURNO = '1ºTURNO'
GROUP BY T.TIPO_VOTO

--NUMERO DE VOTOS POR TIPO DO VOTO(NULOS) NO 2 TURNO
SELECT T.TIPO_VOTO,ISNULL(SUM(V.QUANTIDADE_VOTOS),0) TOTAL
FROM FATO_VOTO V
RIGHT JOIN DIM_TIPO_VOTO T
ON(V.ID_TIPO_VOTO = T.ID_TIPO_VOTO)
RIGHT JOIN DIM_TEMPO TE
ON (V.DIA_VOTACAO = TE.ID_TEMPO)
WHERE T.TIPO_VOTO = 'NULOS' AND TE.ANO = '2022' AND TE.TURNO = '2ºTURNO'
GROUP BY T.TIPO_VOTO

--NUMERO DE VOTOS POR TIPO DO VOTO(VALIDOS)
SELECT T.TIPO_VOTO,ISNULL(SUM(V.QUANTIDADE_VOTOS),0) TOTAL
FROM FATO_VOTO V
RIGHT JOIN DIM_TIPO_VOTO T
ON(V.ID_TIPO_VOTO = T.ID_TIPO_VOTO)
RIGHT JOIN DIM_TEMPO TE
ON (V.DIA_VOTACAO = TE.ID_TEMPO)
WHERE T.TIPO_VOTO = 'VALIDOS' AND TE.ANO = '2022' AND TE.TURNO = '1ºTURNO'
GROUP BY T.TIPO_VOTO

--NUMERO DE VOTOS POR TIPO DO VOTO(VALIDOS) NO 2 TURNO
SELECT T.TIPO_VOTO,ISNULL(SUM(V.QUANTIDADE_VOTOS),0) TOTAL
FROM FATO_VOTO V
RIGHT JOIN DIM_TIPO_VOTO T
ON(V.ID_TIPO_VOTO = T.ID_TIPO_VOTO)
RIGHT JOIN DIM_TEMPO TE
ON (V.DIA_VOTACAO = TE.ID_TEMPO)
WHERE T.TIPO_VOTO = 'VALIDOS' AND TE.ANO = '2022' AND TE.TURNO = '2ºTURNO'
GROUP BY T.TIPO_VOTO

--QUANTIDADE DE VOTOS POR CANDIDATOS, CIDADE E ESTADO
SELECT C.NM_CANDIDATO,L.LOCALIDADE,L.UF_ESTADO,ISNULL(SUM(V.QUANTIDADE_VOTOS),0) TOTAL
FROM FATO_VOTO V
RIGHT JOIN DIM_CANDIDATO C
ON(V.ID_CANDIDATO = C.ID_CANDIDATO)
RIGHT JOIN DIM_LOCALIDADE_ELEICAO L
ON(V.ID_LOCALIDADE_ELEICAO = L.ID_LOCALIDADE_ELEICAO)
RIGHT JOIN DIM_TEMPO TE
ON (V.DIA_VOTACAO = TE.ID_TEMPO)
WHERE C.NM_CANDIDATO = 'BOLSONARO' AND TE.ANO = '2022' AND TE.TURNO = '1ºTURNO'
GROUP BY C.NM_CANDIDATO, L.LOCALIDADE, L.UF_ESTADO
 
--QUANTIDADE DE VOTOS POR CANDIDATOS, CIDADE E ESTADO NO 2 TURNO
SELECT C.NM_CANDIDATO,L.LOCALIDADE,L.UF_ESTADO,ISNULL(SUM(V.QUANTIDADE_VOTOS),0) TOTAL
FROM FATO_VOTO V
RIGHT JOIN DIM_CANDIDATO C
ON(V.ID_CANDIDATO = C.ID_CANDIDATO)
RIGHT JOIN DIM_LOCALIDADE_ELEICAO L
ON(V.ID_LOCALIDADE_ELEICAO = L.ID_LOCALIDADE_ELEICAO)
RIGHT JOIN DIM_TEMPO TE
ON (V.DIA_VOTACAO = TE.ID_TEMPO)
WHERE C.NM_CANDIDATO = 'BOLSONARO' AND TE.ANO = '2022' AND TE.TURNO = '2ºTURNO'
GROUP BY C.NM_CANDIDATO, L.LOCALIDADE, L.UF_ESTADO

--NUMERO DE VOTOS POR CANDIDATO EM UM ESTADO EM UMA DETERMINDA SEÇÃO 
SELECT C.NM_CANDIDATO,S.NM_SECAO,L.LOCALIDADE,L.UF_ESTADO,ISNULL(SUM(V.QUANTIDADE_VOTOS),0) TOTAL
FROM FATO_VOTO V
FULL JOIN DIM_CANDIDATO C
ON(V.ID_CANDIDATO = C.ID_CANDIDATO)
FULL JOIN DIM_LOCALIDADE_ELEICAO L
ON(V.ID_LOCALIDADE_ELEICAO = L.ID_LOCALIDADE_ELEICAO)
FULL JOIN DIM_SECAO S
ON(V.ID_SECAO = S.ID_SECAO)
FULL JOIN DIM_TEMPO TE
ON (V.DIA_VOTACAO = TE.ID_TEMPO)
WHERE S.NM_SECAO = '145'AND TE.ANO = '2022' AND TE.TURNO = '1ºTURNO'
GROUP BY C.NM_CANDIDATO,S.NM_SECAO, L.LOCALIDADE, L.UF_ESTADO

--NUMERO DE VOTOS POR CANDIDATO EM UM ESTADO EM UMA DETERMINDA SEÇÃO 
SELECT C.NM_CANDIDATO,S.NM_SECAO,L.LOCALIDADE,L.UF_ESTADO,ISNULL(SUM(V.QUANTIDADE_VOTOS),0) TOTAL
FROM FATO_VOTO V
FULL JOIN DIM_CANDIDATO C
ON(V.ID_CANDIDATO = C.ID_CANDIDATO)
FULL JOIN DIM_LOCALIDADE_ELEICAO L
ON(V.ID_LOCALIDADE_ELEICAO = L.ID_LOCALIDADE_ELEICAO)
FULL JOIN DIM_SECAO S
ON(V.ID_SECAO = S.ID_SECAO)
FULL JOIN DIM_TEMPO TE
ON (V.DIA_VOTACAO = TE.ID_TEMPO)
WHERE S.NM_SECAO = '145'AND TE.ANO = '2022' AND TE.TURNO = '2ºTURNO'
GROUP BY C.NM_CANDIDATO,S.NM_SECAO, L.LOCALIDADE, L.UF_ESTADO


--NUMERO DE VOTOS POR PARTIDO
SELECT C.PARTIDO,ISNULL(SUM(V.QUANTIDADE_VOTOS),0) TOTAL
FROM FATO_VOTO V
RIGHT JOIN DIM_CANDIDATO C
ON(V.ID_CANDIDATO = C.ID_CANDIDATO)
RIGHT JOIN DIM_TEMPO T
ON (V.DIA_VOTACAO = T.ID_TEMPO)
WHERE T.ANO = '2022' AND T.TURNO = '1ºTURNO'
GROUP BY C.PARTIDO

--NUMERO DE VOTOS POR PARTIDO NO 2 TURNO
SELECT C.PARTIDO,ISNULL(SUM(V.QUANTIDADE_VOTOS),0) TOTAL
FROM FATO_VOTO V
RIGHT JOIN DIM_CANDIDATO C
ON(V.ID_CANDIDATO = C.ID_CANDIDATO)
RIGHT JOIN DIM_TEMPO T
ON (V.DIA_VOTACAO = T.ID_TEMPO)
WHERE T.ANO = '2022' AND T.TURNO = '2ºTURNO'
GROUP BY C.PARTIDO

--NUMERO DE VOTOS POR PARTIDO EM UMA LOCALIDADE
SELECT C.PARTIDO,L.ESTADO, L.CIDADE,ISNULL(SUM(V.QUANTIDADE_VOTOS),0) TOTAL
FROM FATO_VOTO V
JOIN DIM_LOCALIDADE L
ON(L.ID_LOCALIDADE = V.ID_LOCALIDADE)
JOIN DIM_CANDIDATO C
ON(V.ID_CANDIDATO = C.ID_CANDIDATO)
JOIN DIM_TEMPO T
ON (V.DIA_VOTACAO = T.ID_TEMPO)
WHERE T.ANO = '2022' AND T.TURNO = '1ºTURNO'
GROUP BY C.PARTIDO, L.ESTADO, L.CIDADE

--NUMERO DE VOTOS POR PARTIDO EM UMA LOCALIDADE NO 2 TURNO
SELECT C.PARTIDO,L.ESTADO, L.CIDADE,ISNULL(SUM(V.QUANTIDADE_VOTOS),0) TOTAL
FROM FATO_VOTO V
JOIN DIM_LOCALIDADE L
ON(L.ID_LOCALIDADE = V.ID_LOCALIDADE)
JOIN DIM_CANDIDATO C
ON(V.ID_CANDIDATO = C.ID_CANDIDATO)
JOIN DIM_TEMPO T
ON (V.DIA_VOTACAO = T.ID_TEMPO)
WHERE T.ANO = '2022' AND T.TURNO = '2ºTURNO'
GROUP BY C.PARTIDO, L.ESTADO, L.CIDADE

--NUMERO DE VOTOS POR CANDIDATO DE UM PARTIDO
SELECT C.PARTIDO,C.NM_CANDIDATO,ISNULL(SUM(V.QUANTIDADE_VOTOS),0) TOTAL
FROM FATO_VOTO V
RIGHT JOIN DIM_CANDIDATO C
ON(V.ID_CANDIDATO = C.ID_CANDIDATO)
JOIN DIM_TEMPO T
ON (V.DIA_VOTACAO = T.ID_TEMPO)
WHERE T.ANO = '2022' AND T.TURNO = '1ºTURNO' AND C.PARTIDO = 'PARTIDO DOS TRABALHADORES'
GROUP BY C.PARTIDO, C.NM_CANDIDATO


--NUMERO DE VOTOS POR CANDIDATO DE UM PARTIDO NO 2 TURNO
SELECT C.PARTIDO,C.NM_CANDIDATO,ISNULL(SUM(V.QUANTIDADE_VOTOS),0) TOTAL
FROM FATO_VOTO V
RIGHT JOIN DIM_CANDIDATO C
ON(V.ID_CANDIDATO = C.ID_CANDIDATO)
JOIN DIM_TEMPO T
ON (V.DIA_VOTACAO = T.ID_TEMPO)
WHERE T.ANO = '2022' AND T.TURNO = '2ºTURNO' AND C.PARTIDO = 'PARTIDO DOS TRABALHADORES'
GROUP BY C.PARTIDO, C.NM_CANDIDATO
