use bd_eleicao

CREATE OR ALTER PROCEDURE SP_OLTP_LOCALIDADE_ELEICAO(@DATA_CARGA DATETIME)
AS BEGIN
       DELETE FROM AUX_LOCALIDADE_ELEICAO WHERE @DATA_CARGA = DATA_CARGA
	   INSERT INTO AUX_LOCALIDADE_ELEICAO(DATA_CARGA, COD_LOCALIDADE_ELEICAO, LOCALIDADE, TIPO_LOCALIDADE, UF_ESTADO)
	   SELECT @DATA_CARGA, L.ID_LOCALIDADE_ELEICAO, L.LOCALIDADE, L.TIPO_LOCALIDADE, L.UF_ESTADO FROM TB_LOCALIDADE_ELEICAO L
       
END