use bd_eleicao

CREATE OR ALTER PROCEDURE SP_OLTP_CANDIDATO(@DATA_CARGA DATETIME) AS 
BEGIN
     DELETE FROM AUX_CANDIDATO WHERE @DATA_CARGA = DATA_CARGA

     INSERT INTO AUX_CANDIDATO (DATA_CARGA, COD_CANDIDATO, NM_CANDIDATO, CPF, COD_CARGO, CARGO, COD_PARTIDO, PARTIDO,CNPJ)
	 SELECT @DATA_CARGA, C.ID_CANDIDATO, C.NM_CANDIDATO, C.CPF, CA.ID_CARGO, CA.NM_CARGO, P.ID_PARTIDO, P.NM_PARTIDO, P.CNPJ
	 FROM TB_CARGO CA JOIN TB_CANDIDATO C 
	 ON(CA.ID_CARGO = C.ID_CARGO) 
	 JOIN TB_PARTIDO P 
	 ON(P.ID_PARTIDO = C.ID_PARTIDO)

END

SELECT * FROM AUX_CANDIDATO

SELECT * FROM TB_CANDIDATO