CREATE OR ALTER PROCEDURE SP_OLTP_SESSAO(@DATA_CARGA DATETIME)
AS
BEGIN
	DELETE AUX_SECAO
	WHERE DATA_CARGA = @DATA_CARGA
	INSERT INTO AUX_SECAO(DATA_CARGA, COD_SECAO, NM_SECAO, ZONA)
	SELECT @DATA_CARGA, ID_SECAO, SECAO, ZONA FROM TB_SECAO
END

EXEC SP_OLTP_SESSAO '20221110'
SELECT * FROM AUX_SECAO