
CREATE OR ALTER PROCEDURE SP_OLTP_TEMPO(@DATA_CARGA DATETIME)
AS
BEGIN
	DELETE AUX_TEMPO
	WHERE DATA_CARGA = @DATA_CARGA
	INSERT INTO AUX_TEMPO(DATA_CARGA, COD_ANO_TURNO, ANO, TURNO)
	SELECT @DATA_CARGA, ID_ANO_TURNO, ANO, TURNO FROM TB_ANO_TURNO
END
EXEC SP_OLTP_TEMPO '20221103' 
