
CREATE OR ALTER PROCEDURE SP_OLTP_ELEITOR(@DATA_CARGA DATETIME)
AS
BEGIN
	DELETE AUX_ELEITOR
	WHERE DATA_CARGA = @DATA_CARGA
	INSERT INTO AUX_ELEITOR(DATA_CARGA, COD_ELEITOR, CPF, NM_SESSAO, ZONA)
	SELECT @DATA_CARGA, ID_ELEITOR, CPF, SECAO, ZONA FROM TB_ELEITOR
END

EXEC SP_OLTP_ELEITOR '20221103'

