CREATE OR ALTER PROCEDURE SP_OLTP_SESSAO(@DATA_CARGA DATETIME)
AS
BEGIN
	DELETE AUX_SESSAO
	WHERE DATA_CARGA = @DATA_CARGA
	INSERT INTO AUX_SESSAO(DATA_CARGA, COD_SESSAO, NM_SESSAO, ZONA)
	SELECT @DATA_CARGA, ID_SESSAO, SESSAO, ZONA FROM TB_SESSAO
END