use bd_eleicao

CREATE OR ALTER PROCEDURE SP_AUX_VOTO(@DATA_CARGA DATETIME)
AS BEGIN
       INSERT INTO AUX_VOTO(DATA_CARGA, COD_ELEITOR, COD_TIPO_VOTO, COD_CANDIDATO, COD_CIDADE, COD_ESTADO, COD_SESSAO, COD_CARGO, COD_LOCALIDADE_ELEICAO)
	   SELECT @DATA_CARGA, E.ID_ELEITOR, T.ID_TIPO_VOTO, C.ID_CANDIDATO, CI.ID_CIDADE, ES.ID_ESTADO, S.ID_SESSAO, CA.ID_CARGO, L.ID_LOCALIDADE_ELEICAO 
	   FROM TB_ELEITOR E JOIN TB_VOTO V 
	   ON(E.ID_ELEITOR = V.ID_ELEITOR)
	   JOIN TB_CANDIDATO C
	   ON(C.ID_CANDIDATO = V.ID_CANDIDATO)
	   JOIN TB_SESSAO S
	   ON(S.ID_CANDIDATO = V.ID_CANDIDATO AND S.ID_ELEITOR = V.ID_ELEITOR)
	   JOIN TB_CIDADE CI
	   ON(S.ID_CIDADE = CI.ID_CIDADE)
	   JOIN TB_ESTADO ES
	   ON(CI.ID_ESTADO = ES.ID_ESTADO)
	   JOIN TB_CARGO CA
	   ON(CA.ID_CARGO = C.ID_CARGO)
	   JOIN TB_LOCALIDADE_ELEICAO L
	   ON(L.ID_LOCALIDADE_ELEICAO = V.ID_LOCALIDADE_ELEICAO)
	   JOIN TB_TIPO_VOTO T
	   ON(T.ID_TIPO_VOTO = V.ID_TIPO_VOTO)

END