use bd_eleicao

CREATE OR ALTER PROCEDURE SP_OLTP_CARGO(@DATA_CARGA DATETIME)
AS BEGIN
        DELETE FROM AUX_CARGO WHERE @DATA_CARGA = DATA_CARGA
		INSERT INTO AUX_CARGO(DATA_CARGA, CARGO)
		SELECT @DATA_CARGA, NM_CARGO FROM TB_CARGO

END
EXEC SP_OLTP_CARGO '20221103'
SELECT * FROM AUX_CARGO