
--NUMERO DE VOTOS POR CARGO
SELECT C.CARGO,SUM(V.QUANTIDADE_VOTOS) TOTAL
FROM FATO_VOTO V
RIGHT JOIN DIM_CARGO C
ON(V.ID_CARGO = C.ID_CARGO)
GROUP BY C.CARGO

--NUMERO DE VOTOS POR PARTIDO
SELECT C.PARTIDO,SUM(V.QUANTIDADE_VOTOS) TOTAL
FROM FATO_VOTO V
RIGHT JOIN DIM_CANDIDATO C
ON(V.ID_CANDIDATO = C.ID_CANDIDATO)
GROUP BY C.PARTIDO

--NUMERO DE VOTOS POR SESSÃO
SELECT S.NM_SESSAO,SUM(V.QUANTIDADE_VOTOS) TOTAL
FROM FATO_VOTO V
RIGHT JOIN DIM_SESSAO S
ON(V.ID_SESSAO = S.ID_SESSAO)
GROUP BY S.NM_SESSAO

--NUMERO DE VOTOS POR TIPO DO VOTO(BRANCOS)
SELECT T.TIPO_VOTO,SUM(V.QUANTIDADE_VOTOS) TOTAL
FROM FATO_VOTO V
RIGHT JOIN DIM_TIPO_VOTO T
ON(V.ID_TIPO_VOTO = T.ID_TIPO_VOTO)
WHERE T.TIPO_VOTO = 'BRANCOS'
GROUP BY T.TIPO_VOTO

--NUMERO DE VOTOS POR TIPO DO VOTO(NULOS)
SELECT T.TIPO_VOTO,SUM(V.QUANTIDADE_VOTOS) TOTAL
FROM FATO_VOTO V
RIGHT JOIN DIM_TIPO_VOTO T
ON(V.ID_TIPO_VOTO = T.ID_TIPO_VOTO)
WHERE T.TIPO_VOTO = 'NULOS'
GROUP BY T.TIPO_VOTO

--NUMERO DE VOTOS POR TIPO DO VOTO(VALIDOS)
SELECT T.TIPO_VOTO,SUM(V.QUANTIDADE_VOTOS) TOTAL
FROM FATO_VOTO V
RIGHT JOIN DIM_TIPO_VOTO T
ON(V.ID_TIPO_VOTO = T.ID_TIPO_VOTO)
WHERE T.TIPO_VOTO = 'VALIDOS'
GROUP BY T.TIPO_VOTO