CREATE OR ALTER PROCEDURE SP_DIM_TIPO_VOTO
AS
BEGIN
	INSERT INTO DIM_TIPO_VOTO(COD_TIPO_VOTO, TIPO_VOTO)
	SELECT COD_TIPO_VOTO, TIPO_VOTO FROM AUX_TIPO_VOTO
END
EXEC SP_DIM_TIPO_VOTO
SELECT * FROM DIM_TIPO_VOTO