use bd_eleicao

CREATE OR ALTER PROCEDURE SP_DIM_CANDIDATO
AS BEGIN
        INSERT INTO DIM_CANDIDATO(COD_CANDIDATO, NM_CANDIDATO,CPF, COD_CARGO,CARGO,COD_PARTIDO,PARTIDO,CNPJ)
		SELECT COD_CANDIDATO, NM_CANDIDATO, CPF, COD_CARGO, CARGO, COD_PARTIDO, PARTIDO, CNPJ FROM AUX_CANDIDATO
END