USE bd_eleicao

CREATE OR ALTER PROCEDURE SP_DIM_LOCALIDADE_ELEICAO
AS BEGIN
      INSERT INTO DIM_LOCALIDADE_ELEICAO(LOCALIDADE,TIPO_LOCALIDADE,UF_ESTADO)
	  SELECT LOCALIDADE,TIPO_LOCALIDADE,UF_ESTADO FROM AUX_LOCALIDADE_ELEICAO
END
EXEC SP_DIM_LOCALIDADE_ELEICAO
SELECT * FROM DIM_LOCALIDADE_ELEICAO