USE bd_eleicao

CREATE OR ALTER PROCEDURE SP_DIM_CARGO
AS BEGIN
       INSERT INTO DIM_CARGO(COD_CARGO, CARGO)
	   SELECT COD_CARGO, CARGO FROM AUX_CARGO
END
EXEC SP_DIM_CARGO
SELECT * FROM DIM_CARGO
