CREATE OR ALTER PROCEDURE SP_DIM_SESSAO
AS
BEGIN
	INSERT INTO DIM_SESSAO(COD_SESSAO, NM_SESSAO, ZONA)
	SELECT COD_SESSAO, NM_SESSAO, ZONA FROM AUX_SESSAO
END
EXEC SP_DIM_SESSAO
SELECT * FROM DIM_SESSAO