USE bd_eleicao

CREATE OR ALTER PROCEDURE SP_DIM_VOTO
AS BEGIN
      DECLARE @COD_ELEITOR INT, @COD_TIPO_VOTO INT, @COD_CANDIDATO INT, @COD_CIDADE INT, @COD_ESTADO INT, @COD_SECAO INT, @COD_CARGO INT,
	  @COD_LOCALIDADE_ELEICAO INT, @COD_ANO_TURNO INT, @ID_LOCALIDADE INT, @ID_CANDIDATO INT, @ID_ELEITOR INT, @ID_SECAO INT, @ID_CARGO INT, @ID_TIPO_VOTO INT,
	  @ID_LOCALIDADE_ELEICAO INT, @DIA_VOTACAO INT, @DATA_CARGA DATETIME
 
      DECLARE C_VOTO CURSOR FOR SELECT COD_ELEITOR, COD_TIPO_VOTO, COD_CANDIDATO, COD_CIDADE, COD_ESTADO, COD_SECAO, COD_CARGO,
	  COD_LOCALIDADE_ELEICAO, COD_ANO_TURNO, DATA_CARGA FROM AUX_VOTO
	  OPEN C_VOTO
	  FETCH C_VOTO INTO @COD_ELEITOR, @COD_TIPO_VOTO, @COD_CANDIDATO, @COD_CIDADE, @COD_ESTADO, @COD_SECAO, @COD_CARGO,
	  @COD_LOCALIDADE_ELEICAO, @COD_ANO_TURNO, @DATA_CARGA

	  WHILE(@@FETCH_STATUS = 0)
	  BEGIN
	      SET @ID_LOCALIDADE = (SELECT ID_LOCALIDADE FROM DIM_LOCALIDADE WHERE @COD_ESTADO = COD_ESTADO AND @COD_CIDADE = COD_CIDADE)
		  SET @ID_CANDIDATO = (SELECT ID_CANDIDATO FROM DIM_CANDIDATO WHERE @COD_CANDIDATO = COD_CANDIDATO)
		  SET @ID_ELEITOR = (SELECT ID_ELEITOR FROM DIM_ELEITOR WHERE @COD_ELEITOR = COD_ELEITOR)
		  SET @ID_SECAO = (SELECT ID_SECAO FROM DIM_SECAO WHERE @COD_SECAO = COD_SECAO)
		  SET @ID_LOCALIDADE_ELEICAO = (SELECT ID_LOCALIDADE_ELEICAO FROM DIM_LOCALIDADE_ELEICAO WHERE @COD_LOCALIDADE_ELEICAO = COD_LOCALIDADE_ELEICAO)
		  SET @ID_CARGO = (SELECT ID_CARGO FROM DIM_CARGO WHERE @COD_CARGO = COD_CARGO)
		  SET @ID_TIPO_VOTO = (SELECT ID_TIPO_VOTO FROM DIM_TIPO_VOTO WHERE @COD_TIPO_VOTO = COD_TIPO_VOTO)
		  SET @DIA_VOTACAO = (SELECT ID_TEMPO FROM DIM_TEMPO WHERE @COD_ANO_TURNO = COD_ANO_TURNO)

	       IF (@ID_LOCALIDADE IS NOT NULL AND
		       @ID_CANDIDATO IS NOT NULL AND
			   @ID_ELEITOR IS NOT NULL AND
			   @ID_SECAO IS NOT NULL AND
			   @ID_LOCALIDADE_ELEICAO IS NOT NULL AND
			   @ID_CARGO IS NOT NULL AND
			   @ID_TIPO_VOTO IS NOT NULL AND
			   @DIA_VOTACAO IS NOT NULL)       
			  BEGIN
			     
			      INSERT INTO FATO_VOTO(ID_ELEITOR, ID_TIPO_VOTO, ID_CANDIDATO, ID_LOCALIDADE, ID_SECAO, DIA_VOTACAO, ID_CARGO, ID_LOCALIDADE_ELEICAO) 
				  VALUES(@ID_ELEITOR, @ID_TIPO_VOTO,@ID_CANDIDATO, @ID_LOCALIDADE, @ID_SECAO, @DIA_VOTACAO, @ID_CARGO, @ID_LOCALIDADE_ELEICAO)
			 END
			 ELSE
			   IF (@ID_LOCALIDADE IS NULL)
			   BEGIN
			       INSERT INTO AUX_VIOLACAO(DATA_CARGA, ID_ELEITOR, ID_TIPO_VOTO, ID_CANDIDATO, ID_LOCALIDADE, ID_SECAO, DIA_VOTACAO, ID_CARGO, ID_LOCALIDADE_ELEICAO, ERRO)
				   VALUES(@DATA_CARGA, @ID_ELEITOR,@ID_TIPO_VOTO,@ID_CANDIDATO, @ID_LOCALIDADE, @ID_SECAO, @DIA_VOTACAO, @ID_CARGO, @ID_LOCALIDADE_ELEICAO,'SEM O ID LOCALIDADE, OU SEJA NAO TEM COD DO ESTADO OU O COD DA CIDADE')
			   END
			    IF (@ID_CANDIDATO IS NULL)
			   BEGIN
			       INSERT INTO AUX_VIOLACAO(DATA_CARGA, ID_ELEITOR, ID_TIPO_VOTO, ID_CANDIDATO, ID_LOCALIDADE, ID_SECAO, DIA_VOTACAO, ID_CARGO, ID_LOCALIDADE_ELEICAO, ERRO)
				   VALUES(@DATA_CARGA, @ID_ELEITOR,@ID_TIPO_VOTO,@ID_CANDIDATO, @ID_LOCALIDADE, @ID_SECAO, @DIA_VOTACAO, @ID_CARGO, @ID_LOCALIDADE_ELEICAO,'SEM O ID CANDIDATO')
			   END
			   IF (@ID_ELEITOR IS NULL)
			   BEGIN
			       INSERT INTO AUX_VIOLACAO(DATA_CARGA, ID_ELEITOR, ID_TIPO_VOTO, ID_CANDIDATO, ID_LOCALIDADE, ID_SECAO, DIA_VOTACAO, ID_CARGO, ID_LOCALIDADE_ELEICAO, ERRO)
				   VALUES(@DATA_CARGA, @ID_ELEITOR,@ID_TIPO_VOTO,@ID_CANDIDATO, @ID_LOCALIDADE, @ID_SECAO, @DIA_VOTACAO, @ID_CARGO, @ID_LOCALIDADE_ELEICAO,'SEM O COD ELEITOR')
			   END
			   IF (@ID_SECAO IS NULL)
			   BEGIN
			       INSERT INTO AUX_VIOLACAO(DATA_CARGA, ID_ELEITOR, ID_TIPO_VOTO, ID_CANDIDATO, ID_LOCALIDADE, ID_SECAO, DIA_VOTACAO, ID_CARGO, ID_LOCALIDADE_ELEICAO, ERRO)
				   VALUES(@DATA_CARGA, @ID_ELEITOR,@ID_TIPO_VOTO,@ID_CANDIDATO, @ID_LOCALIDADE, @ID_SECAO, @DIA_VOTACAO, @ID_CARGO, @ID_LOCALIDADE_ELEICAO,'SEM O COD SECAO')
			   END
			   IF (@ID_LOCALIDADE_ELEICAO IS NULL)
			   BEGIN
			       INSERT INTO AUX_VIOLACAO(DATA_CARGA, ID_ELEITOR, ID_TIPO_VOTO, ID_CANDIDATO, ID_LOCALIDADE, ID_SECAO, DIA_VOTACAO, ID_CARGO, ID_LOCALIDADE_ELEICAO, ERRO)
				   VALUES(@DATA_CARGA,@ID_ELEITOR,@ID_TIPO_VOTO,@ID_CANDIDATO, @ID_LOCALIDADE, @ID_SECAO, @DIA_VOTACAO, @ID_CARGO, @ID_LOCALIDADE_ELEICAO,'SEM O ID LOCALIDADE ELEICAO')
			   END
			   IF (@ID_CARGO IS NULL)
			   BEGIN
			       INSERT INTO AUX_VIOLACAO(DATA_CARGA, ID_ELEITOR, ID_TIPO_VOTO, ID_CANDIDATO, ID_LOCALIDADE, ID_SECAO, DIA_VOTACAO, ID_CARGO, ID_LOCALIDADE_ELEICAO, ERRO)
				   VALUES(@DATA_CARGA, @ID_ELEITOR,@ID_TIPO_VOTO,@ID_CANDIDATO, @ID_LOCALIDADE, @ID_SECAO, @DIA_VOTACAO, @ID_CARGO, @ID_LOCALIDADE_ELEICAO,'SEM O COD CARGO')
			   END
			   IF (@ID_TIPO_VOTO IS NULL)
			   BEGIN
			       INSERT INTO AUX_VIOLACAO(DATA_CARGA, ID_ELEITOR, ID_TIPO_VOTO, ID_CANDIDATO, ID_LOCALIDADE, ID_SECAO, DIA_VOTACAO, ID_CARGO, ID_LOCALIDADE_ELEICAO, ERRO)
				   VALUES(@DATA_CARGA, @ID_ELEITOR,@ID_TIPO_VOTO,@ID_CANDIDATO, @ID_LOCALIDADE, @ID_SECAO, @DIA_VOTACAO, @ID_CARGO, @ID_LOCALIDADE_ELEICAO,'SEM O COD TIPO_VOTO')
			   END
			   IF (@DIA_VOTACAO IS NULL)
			   BEGIN
			       INSERT INTO AUX_VIOLACAO(DATA_CARGA, ID_ELEITOR, ID_TIPO_VOTO, ID_CANDIDATO, ID_LOCALIDADE, ID_SECAO, DIA_VOTACAO, ID_CARGO, ID_LOCALIDADE_ELEICAO, ERRO)
				   VALUES(@DATA_CARGA, @ID_ELEITOR,@ID_TIPO_VOTO,@ID_CANDIDATO, @ID_LOCALIDADE, @ID_SECAO, @DIA_VOTACAO, @ID_CARGO, @ID_LOCALIDADE_ELEICAO,'SEM O O COD TURNO DA ELEICAO, NA DIMENSAO TEMPO')
			   END
			  
			    	   
	       FETCH C_VOTO INTO @COD_ELEITOR, @COD_TIPO_VOTO, @COD_CANDIDATO, @COD_CIDADE, @COD_ESTADO, @COD_SECAO, @COD_CARGO,
		   @COD_LOCALIDADE_ELEICAO, @COD_ANO_TURNO, @DATA_CARGA
	  END
	  CLOSE C_VOTO
	  DEALLOCATE C_VOTO
END
EXEC SP_DIM_VOTO

SELECT * FROM FATO_VOTO

DELETE FROM FATO_VOTO

SELECT * FROM AUX_VIOLACAO


