USE bd_eleicao

CREATE OR ALTER PROCEDURE SP_DIM_VOTO
AS BEGIN
      DECLARE @COD_ELEITOR INT, @COD_TIPO_VOTO INT, @COD_CANDIDATO INT, @COD_CIDADE INT, @COD_ESTADO INT, @COD_SESSAO INT, @COD_CARGO INT,
	  @COD_LOCALIDADE_ELEICAO INT, @COD_ANO_TURNO INT, @ID_LOCALIDADE INT, @ID_CANDIDATO INT, @ID_ELEITOR INT, @ID_SESSAO INT, @ID_CARGO INT, @ID_TIPO_VOTO INT,
	  @ID_LOCALIDADE_ELEICAO INT, @DIA_VOTACAO INT
 
      DECLARE C_VOTO CURSOR FOR SELECT COD_ELEITOR, COD_TIPO_VOTO, COD_CANDIDATO, COD_CIDADE, COD_ESTADO, COD_SESSAO, COD_CARGO
	  COD_LOCALIDADE_ELEICAO, COD_ANO_TURNO FROM AUX_VOTO
	  OPEN C_VOTO
	  FETCH C_VOTO INTO @COD_ELEITOR, @COD_TIPO_VOTO, @COD_CANDIDATO, @COD_CIDADE, @COD_ESTADO, @COD_SESSAO, @COD_CARGO,
	  @COD_LOCALIDADE_ELEICAO, @COD_ANO_TURNO 
	  WHILE(@@FETCH_STATUS = 0)
	  BEGIN
	       IF (EXISTS (SELECT 1 FROM DIM_LOCALIDADE L WHERE @COD_CIDADE = L.COD_CIDADE AND @COD_ESTADO = L.COD_ESTADO) AND
		      EXISTS (SELECT 1 FROM DIM_ELEITOR E WHERE @COD_ELEITOR = E.COD_ELEITOR) AND
			  EXISTS (SELECT 1 FROM DIM_CANDIDATO C WHERE @COD_CANDIDATO = C.COD_CANDIDATO) AND
			  EXISTS (SELECT 1 FROM DIM_SESSAO S WHERE @COD_SESSAO = S.COD_SESSAO) AND
			  EXISTS (SELECT 1 FROM DIM_CARGO C WHERE @COD_CARGO = C.COD_CARGO) AND
			  EXISTS (SELECT 1 FROM DIM_TIPO_VOTO T WHERE @COD_TIPO_VOTO = T.COD_TIPO_VOTO) AND
			  EXISTS (SELECT 1 FROM DIM_LOCALIDADE_ELEICAO LE WHERE @COD_LOCALIDADE_ELEICAO = LE.COD_LOCALIDADE_ELEICAO) AND
			  EXISTS (SELECT 1 FROM DIM_TEMPO T WHERE @COD_ANO_TURNO = COD_ANO_TURNO))       
			  BEGIN

			      SET @ID_LOCALIDADE = (SELECT ID_LOCALIDADE FROM DIM_LOCALIDADE WHERE @COD_ESTADO = COD_ESTADO AND @COD_CIDADE = COD_CIDADE)
				  SET @ID_CANDIDATO = (SELECT ID_CANDIDATO FROM DIM_CANDIDATO WHERE @COD_CANDIDATO = COD_CANDIDATO)
				  SET @ID_ELEITOR = (SELECT ID_ELEITOR FROM DIM_ELEITOR WHERE @COD_ELEITOR = COD_ELEITOR)
				  SET @ID_SESSAO = (SELECT ID_SESSAO FROM DIM_SESSAO WHERE @COD_SESSAO = COD_SESSAO)
				  SET @ID_LOCALIDADE_ELEICAO = (SELECT ID_LOCALIDADE_ELEICAO FROM DIM_LOCALIDADE_ELEICAO WHERE @COD_LOCALIDADE_ELEICAO = COD_LOCALIDADE_ELEICAO)
				  SET @ID_CARGO = (SELECT ID_CARGO FROM DIM_CARGO WHERE @COD_CARGO = COD_CARGO)
				  SET @ID_TIPO_VOTO = (SELECT ID_TIPO_VOTO FROM DIM_TIPO_VOTO WHERE @COD_TIPO_VOTO = COD_TIPO_VOTO)
				  SET @DIA_VOTACAO = (SELECT ID_TEMPO FROM DIM_TEMPO WHERE @COD_ANO_TURNO = COD_ANO_TURNO)

			      INSERT INTO FATO_VOTO(ID_ELEITOR, ID_TIPO_VOTO, ID_CANDIDATO, ID_LOCALIDADE, ID_SESSAO, DIA_VOTACAO, ID_CARGO, ID_LOCALIDADE_ELEICAO) 
				  VALUES(@ID_ELEITOR, @ID_TIPO_VOTO,@ID_CANDIDATO, @ID_LOCALIDADE, @ID_SESSAO, @DIA_VOTACAO, @ID_CARGO, @ID_LOCALIDADE_ELEICAO)

			 END



	       FETCH C_VOTO INTO @COD_ELEITOR, @COD_TIPO_VOTO, @COD_CANDIDATO, @COD_CIDADE, @COD_ESTADO, @COD_SESSAO, @COD_CARGO, @COD_LOCALIDADE_ELEICAO
	  END
	  CLOSE C_VOTO
	  DEALLOCATE C_VOTO


END
