USE bd_eleicao

CREATE OR ALTER PROCEDURE SP_DIM_VOTO
AS BEGIN
      DECLARE @COD_ELEITOR INT, @COD_TIPO_VOTO INT, @COD_CANDIDATO INT, @COD_CIDADE INT, @COD_ESTADO INT, @COD_SESSAO INT, @COD_CARGO INT,
	  @COD_LOCALIDADE_ELEICAO INT, @ID_LOCALIDADE INT, @ID_CANDIDATO INT, @ID_ELEITOR INT, @ID_SESSAO INT
 
      DECLARE C_VOTO CURSOR FOR SELECT COD_ELEITOR, COD_TIPO_VOTO, COD_CANDIDATO, COD_CIDADE, COD_ESTADO, COD_SESSAO, COD_CARGO
	  COD_LOCALIDADE_ELEICAO FROM AUX_VOTO
	  OPEN C_VOTO
	  FETCH C_VOTO INTO @COD_ELEITOR, @COD_TIPO_VOTO, @COD_CANDIDATO, @COD_CIDADE, @COD_ESTADO, @COD_SESSAO, @COD_CARGO,
	  @COD_LOCALIDADE_ELEICAO
	  WHILE(@@FETCH_STATUS = 0)
	  BEGIN
	       IF EXISTS ((SELECT 1 FROM DIM_LOCALIDADE L WHERE @COD_CIDADE = L.COD_CIDADE AND @COD_ESTADO = L.COD_ESTADO) AND
		      EXISTS (SELECT 1 FROM DIM_ELEITOR E WHERE @COD_ELEITOR = E.COD_ELEITOR) AND
			  EXISTS (SELECT 1 FROM DIM_CANDIDATO C WHERE @COD_CANDIDATO = C.COD_CANDIDATO) AND
			  EXISTS (SELECT 1 FROM DIM_SESSAO S WHERE @COD_SESSAO = S.COD_SESSAO)
			         )
			  BEGIN
			      SET @ID_LOCALIDADE = (SELECT ID_LOCALIDADE FROM DIM_LOCALIDADE WHERE @COD_ESTADO = COO_ESTADO AND @COD_CIDADE = COD_CIDADE)
				  SET @ID_CANDIDATO = (SELECT ID_CANDIDATO FROM DIM_CANDIDATO WHERE @COD_CANDIDATO = COD_CANDIDATO)
				  SET @ID_ELEITOR = (SELECT ID_ELEITOR FROM DIM_ELEITOR WHERE @COD_ELEITOR = COD_ELEITOR)
				  SET @ID_SESSAO = (SELECT ID_SESSAO FROM DIM_SESSAO WHERE @COD_SESSAO = COD_SESSAO)
			      INSERT INTO FATO_VOTO(@ID_CANDIDATO, @ID_ELEITOR, @ID_LOCALIDADE, @ID_SESSAO)

			 END



	       FETCH C_VOTO INTO @COD_ELEITOR, @COD_TIPO_VOTO, @COD_CANDIDATO, @COD_CIDADE, @COD_ESTADO, @COD_SESSAO, @COD_CARGO, @COD_LOCALIDADE_ELEICAO
	  END
	  CLOSE C_VOTO
	  DEALLOCATE C_VOTO


END